<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-F2UU26L" ignored="1" name="Default test" tests="6" failures="1" timestamp="2021-01-15T16:43:45 IST" time="3.019" errors="0">
  <testcase name="testAddProduct" time="0.034" classname="neotech.ProductClientTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method neotech.ProductClientTest.testAddProduct() didn&amp;apos;t finish within the time-out 10">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method neotech.ProductClientTest.testAddProduct() didn't finish within the time-out 10
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$51/3224332.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testAddProduct -->
  <testcase name="testGetAllProducts" time="1.927" classname="neotech.ProductClientTest"/>
  <testcase name="testGetBadRequest" time="0.133" classname="neotech.ProductClientTest"/>
  <testcase name="testGetProduct" time="0.363" classname="neotech.ProductClientTest"/>
  <testcase name="testGetRequestNotFound" time="0.111" classname="neotech.ProductClientTest"/>
  <testcase name="testUpdateProduct" time="0.269" classname="neotech.ProductClientTest"/>
  <testcase name="testDeleteProduct" time="0.0" classname="neotech.ProductClientTest">
    <ignored/>
  </testcase> <!-- testDeleteProduct -->
</testsuite> <!-- Default test -->
